# 练习 7.1

以下函数完全没有检查可能的数据错误以及可能的执行失败。请找出此函数中所有可能发生错误的地方。本题并不考虑出线异常(exception)。

```c++
int *alloc_and_init( string file_name )
{
    ifstream infile( file_name );
    int elem_cnt;
    infile >> elem_cnt;
    int *pi = allocate_array( elem_cnt );

    int elem;
    int index = 0;
    while ( infile >> elem )
        pi[ index++ ] = elem;

    sort_array( pi, elem_cnt );
    register_data( pi );

    return pi;
}
```

# 练习 7.2
下列函数被上题的alloc_and_init()调用，执行失败时会发出异常：

```
allocate_array()  发出异常noMem
sort_array()      发出异常int
register_data()   发出异常string
```

请安置一个或者多个try块，以及相应的catch子句，以便能适当地处理这些异常。相应的catch子句中只需将错误打印出来即可。

```c++
int *alloc_and_init( string file_name )
{
    ifstream infile( file_name.c_str() );
    if ( ! infile ) return 0;

    int elem_cnt;
    infile >> elem_cnt;
    if ( ! infile ) return 0;

    try {
        int *pi = allocate_array( elem_cnt );   // (1)
        int elem;
        int index = 0;
        while ( infile >> elem && index < elem_cnt )
            pi[ index++ ] = elem;

        sort_array( pi, elem_cnt );             // (2)
        register_data( pi );                    // (3)

    } 
    catch( const noMem &memFail ) {             // 异常情况(1)
        cerr << "alloc_and_init(): allocate_array failure!\n"
            << memFail.what() << endl;
        return 0;
    }

    catch( int &sortFail ) {                    // 异常情况(2)
        cerr << "alloc_and_init(): sort_array failure!\n"
            << memFail.what() << endl;
        return 0;
    }

    catch( string &registerFail ) {
        cerr << "alloc_and_init(): register_data failure!\n"
            << "thrown string value: "
            << registerFail << endl;
        return 0;
    }
    return pi; // 如果没有任何异常被抛出，就会被执行到这里......
}
```


# 练习 7.3

为练习5.2的Stack类体系加入两个异常类，处理“想从空Stack中取出元素”和“想为满stack添加元素”两种错误。请显示修改后的pop()和push()

我定义popOnEmpty和pushOnFull两个异常类，分别供pop()和push()抛出。于是，Stack的所有member function就不再需要返回代表成功或失败的值了：

```c++
void pop( elemType &elem )
{
    if ( empty() )
        throw PopOnEmpty();
    elem = _stack[ --_top ];
    _stack.pop_back();
}

void push( const elemType &elem )
{
    if ( full() )
        throw PushOnFull();
    _stack.push_back( elem );
    ++_top;
}

```

为了让这两个Stack异常可以被完全不知情的其他组件捕获，它们应该融入StackException继承体系中，后者又应该派生自标准库所提供的logic_error class。

local_error派生自exception。exception是标准库的所有异常类别继承体系的最根本抽象基类。这个继承体系有一个名为what()的虚函数，会返回const char*，用以表示被捕获的异常究竟为何。

```c++
class StackException: public logic_error {
public:
    StackException( const char* what ): _what( what ){}
    const char *what() const { return _what.c_str(); }

protected:
    string _what;
};

class PopOnEmpty: public StackException {
public:
    PopOnEmpty(): StackException( "Pop on Empty Stack" ){}
};

class PopOnFull: public StackException {
public:
    PopOnEmpty(): StackException( "Push on Full Stack" ){}
};
```

以下任何一个catch子句都能够处理类型为PushOnFull的异常：

```c++
catch( const PushOnFull &pof )
    { log( pof.what() ); return; }

catch( const StackException &stke )
    { log( stke.what() ); return; }

catch( const logic_error &lge )
    { log( lge.what() ); return; }

catch( const exception &ex )
    { log( ex.what() ); return; }
```


